/**
 * The declared balance of a cartera gestionada against its derived value (#1550,
 * ADR 0085) — the witness discipline of #1422 applied to a container.
 *
 * The careo itself lives in `managed-portfolio-reconciliation`; this family only
 * decides which portfolios are asked and dresses the answer as a signal.
 */

import { type DataQualityCollector, signalNaturalKey } from "./data-quality-collector";
import type { ManagedPortfolio } from "./managed-portfolio";
import {
  describeManagedPortfolioDrift,
  managedPortfolioMemberValues,
  reconcileManagedPortfolio,
} from "./managed-portfolio-reconciliation";
import type { MoneyMinor } from "./money";
import type { ManualAsset, Workspace } from "./workspace-types";

/**
 * Machine code for a managed portfolio whose derived value and declared balance
 * disagree beyond the threshold (#1550).
 */
export const PORTFOLIO_DECLARED_VS_DERIVED_CODE = "PORTFOLIO_DECLARED_VS_DERIVED";

export interface DataQualityPortfolioReconciliationInput {
  workspace: Workspace;
  assets: readonly ManualAsset[];
  /**
   * The workspace's carteras gestionadas with their declared balance (#1550).
   * Required, not optional, for the same reason `netUnitsByAssetId` is: a careo
   * only one consumer feeds is a careo the human and the agent disagree about.
   * An empty array is the honest reading of "no managed portfolios".
   */
  managedPortfolios: readonly ManagedPortfolio[];
  /**
   * Each live holding's value AT `asOfDateKey`, from the curve-valued engine and
   * in whatever currency it is held. The careo reads it to sum a portfolio's
   * investment members; a member absent here (or held in another currency) makes
   * the derived side incomplete and silences the careo rather than adding a
   * dollar to a euro (#1401). Required so both consumers quote the same figures
   * the board prints.
   */
  holdingValueByHoldingId: ReadonlyMap<string, MoneyMinor>;
}

/**
 * The derived figure always rules: this signal never adjusts a cent, it only says
 * out loud that the two no longer agree. What it careas is the INVESTMENT members
 * only — the container's cash is deliberately outside the comparison, because the
 * number the owner reads in the manager's app is the market value of the funds
 * and the cash box grows to `150 € + 0,5 %` of the portfolio before being
 * invested (more than ten points of drift generated by design, right before every
 * contribution). `medium`: nothing on screen is provably wrong — a stale NAV, a
 * missing operation, or a mistyped balance all produce this same shape, and only
 * the owner knows which.
 *
 * Members that are no longer live are skipped rather than treated as missing
 * values: they contribute nothing to the derived total the ficha prints either,
 * so the careo reads exactly the composition the human sees.
 */
export const collectPortfolioReconciliationSignals: DataQualityCollector<
  DataQualityPortfolioReconciliationInput
> = (input) => {
  const liveMemberById = new Map(
    input.assets.map((asset) => [
      asset.id,
      { type: asset.type, value: input.holdingValueByHoldingId.get(asset.id) ?? null },
    ]),
  );

  return input.managedPortfolios.flatMap((portfolio) => {
    if (portfolio.witness === null) return [];
    // Scope relevance is decided by OWNERSHIP of its members, exactly as every
    // holding-level signal decides it — not by the portfolio's own `scopeId`.
    // A cartera registered under one member is a real doubt about the household's
    // figure too, because its members sum into it.
    if (!portfolio.holdingIds.some((holdingId) => input.ownedAssetIds.has(holdingId))) {
      return [];
    }

    // The careo reads the WHOLE container (the witness is the container's), and
    // the cash rule lives in the domain builder — one home for both surfaces.
    const members = managedPortfolioMemberValues(portfolio.holdingIds, liveMemberById);

    const reconciliation = reconcileManagedPortfolio({
      baseCurrency: input.workspace.baseCurrency,
      members,
      witness: portfolio.witness,
    });

    if (reconciliation.state !== "diverged") return [];

    return [
      {
        affected: {
          id: portfolio.id,
          label: portfolio.name,
          object: "managed_portfolio" as const,
        },
        category: "portfolio_reconciliation" as const,
        code: PORTFOLIO_DECLARED_VS_DERIVED_CODE,
        fixable: true,
        label: describeManagedPortfolioDrift({
          portfolioName: portfolio.name,
          reconciliation,
        }),
        naturalKey: signalNaturalKey(
          "portfolio_reconciliation",
          PORTFOLIO_DECLARED_VS_DERIVED_CODE,
          portfolio.id,
        ),
        ...(reconciliation.declaredDate === null
          ? {}
          : { observedDate: reconciliation.declaredDate }),
        severity: "medium" as const,
      },
    ];
  });
};
