import { formatDateKeyEs } from "./dates";
import { managedPortfolioMemberRoles } from "./managed-portfolio-members";
import { type CurrencyCode, formatMoneyMinorPrivacy, type MoneyMinor } from "./money";

/**
 * The declared balance of a managed portfolio as a RECONCILIATION WITNESS
 * (ADR 0085, #1550) — pure domain, no persistence and no rendering.
 *
 * The derived figure always rules: the witness never plugs, adjusts, or
 * overrides a single cent of the book (#1422 discipline). Its only job is to
 * disagree out loud when the two drift apart, so somebody looks.
 *
 * **The careo excludes the container's cash.** The number the owner reads in the
 * manager's app is the market value of the FUNDS: MyInvestor's «Valor de
 * mercado» (1.497,37 €) is the sum of the seven funds to the cent, with the
 * 7,34 € of cash in its own box beside it. worthline's own derived total DOES
 * include that cash (it is a sibling member, ADR 0085), so careing the two would
 * compare different things — and not with a constant bias either: the container
 * accumulates cash up to `150 € + 0,5 %` of its value before investing it, which
 * on a ~1.500 € portfolio is more than 10 points of drift generated BY DESIGN,
 * right before every contribution. The witness is therefore compared against the
 * investment members only, and the cash is reported beside it so the ficha can
 * show it the way the manager does.
 */

/**
 * Relative drift beyond which the two figures are declared to disagree, in basis
 * points (ADR 0085: 2 %).
 *
 * NAV freshness alone moves the derived figure ~0,3–1,2 % against a witness typed
 * a day or two earlier (measured on the real Metal fixture), so a tighter
 * threshold would fire on nothing but the calendar. Anything past 2 % is no
 * longer explained by a stale NAV.
 */
export const MANAGED_PORTFOLIO_DRIFT_THRESHOLD_BPS = 200;

/** The last balance the owner read in the manager's app, and the day it belongs to. */
export interface ManagedPortfolioWitness {
  /** The market value of the portfolio's FUNDS — never including its cash box. */
  declaredValue: MoneyMinor;
  /** The day that balance was read, as `YYYY-MM-DD`. */
  declaredDate: string;
}

/** One member's value as the careo reads it; `value` is null when it has none. */
export interface ManagedPortfolioMemberValue {
  holdingId: string;
  /** The member's value at the reconciliation date, or null when unknown. */
  value: MoneyMinor | null;
  /** True for the container's cash sibling — outside the careo by design. */
  isCash: boolean;
  /**
   * True for the "(sin detallar)" aggregate (#1551). It is INSIDE the careo (it
   * is invested money), but reported apart because it is the one summand the
   * owner is expected to shrink: while it still stands for a composition he has
   * begun to detail, the book legitimately reads above the declared balance, and
   * a drift blamed on prices instead of on the aggregate sends him looking in the
   * wrong place.
   */
  isUndetailed: boolean;
}

/** A live member as the builder below reads it: what it is, and what it is worth. */
export interface ManagedPortfolioLiveMember {
  /** The holding's own type (`investment`, `cash`, `manual`, …). */
  type: string;
  /**
   * Its value in the currency it is HELD in — never a converted one. The careo
   * only adds what is natively in the base currency, so a member converted
   * upstream would be careed on a rate the data-health signal cannot see, and
   * the ficha and the signal would judge the same portfolio differently.
   */
  value: MoneyMinor | null;
}

/**
 * Turn a portfolio's membership into the careo's input — the ONE home of two
 * rules every surface would otherwise re-derive (ADR 0085):
 *
 * - **The cash box is the `cash` member**, and only it. A member with a stored
 *   valuation that is not cash (the "(sin detallar)" aggregate of S5, #1551) is
 *   invested money and belongs INSIDE the careo, so the test cannot be "not an
 *   investment".
 * - **A member that is no longer live is skipped**, not counted as missing: it
 *   adds nothing to the derived total the ficha prints either, so the careo reads
 *   exactly the composition the human sees.
 */
export function managedPortfolioMemberValues(
  holdingIds: readonly string[],
  liveMemberById: ReadonlyMap<string, ManagedPortfolioLiveMember>,
): ManagedPortfolioMemberValue[] {
  // The classification is `managedPortfolioMemberRoles`', not a second reading of
  // the same types here: one home, so the careo and the ficha cannot disagree
  // about which member is the cash box and which is the aggregate.
  const roles = managedPortfolioMemberRoles(
    holdingIds,
    new Map([...liveMemberById].map(([holdingId, member]) => [holdingId, member.type])),
  );

  return holdingIds.flatMap((holdingId) => {
    const member = liveMemberById.get(holdingId);
    if (member === undefined) return [];
    return [
      {
        holdingId,
        isCash: holdingId === roles.cashHoldingId,
        isUndetailed: holdingId === roles.undetailedHoldingId,
        value: member.value,
      },
    ];
  });
}

export type ManagedPortfolioReconciliationState =
  /** Nothing typed yet: the ficha invites a witness, nothing is wrong. */
  | "no_witness"
  /** A witness exists but the two figures cannot honestly be compared. */
  | "not_comparable"
  /** Within the threshold — the book and the manager's app agree. */
  | "aligned"
  /** Past the threshold — somebody has to look. */
  | "diverged";

export type ManagedPortfolioNotComparableReason =
  /** No investment member has a value, so there is nothing to compare against. */
  | "no_investment_value"
  /** Some investment member has no honest value in the base currency. */
  | "incomplete_members"
  /** The witness was declared in another currency than the book's. */
  | "currency_mismatch"
  /**
   * The stored balance is not positive, so there is no relative drift to
   * measure. The form refuses one, so this only arrives through an import.
   */
  | "declared_not_positive";

export interface ManagedPortfolioReconciliation {
  state: ManagedPortfolioReconciliationState;
  /** Why the careo was skipped; present only when `state` is `not_comparable`. */
  reason?: ManagedPortfolioNotComparableReason;
  /** The investment members' value — the figure that faces the witness. */
  investmentValue: MoneyMinor;
  /**
   * The part of {@link investmentValue} still standing on the "(sin detallar)"
   * aggregate (#1551), or zero when there is none. Inside the careo, reported
   * apart: it is what explains a book reading above the declared balance
   * mid-substitution, and naming it is the difference between "reduce the
   * aggregate" and a fruitless hunt through prices.
   */
  undetailedValue: MoneyMinor;
  /** The container's cash, reported apart and never careed. */
  cashValue: MoneyMinor;
  /** The witness, echoed for the surfaces that print all three figures. */
  declaredValue: MoneyMinor | null;
  declaredDate: string | null;
  /**
   * `(investment − declared) / declared` in basis points: negative means the
   * book reads BELOW what the manager's app declared. Null without a careo.
   */
  driftBps: number | null;
  thresholdBps: number;
}

/**
 * Face the declared balance against the derived value of the investment members.
 *
 * Deliberately silent rather than accusing whenever the comparison would be
 * dishonest: a member without an honest value in the base currency would make the
 * derived side an incomplete sum (the #1401 shape — never add a dollar to a
 * euro), and a portfolio with no investment value has nothing to compare.
 */
export function reconcileManagedPortfolio(input: {
  baseCurrency: CurrencyCode;
  members: readonly ManagedPortfolioMemberValue[];
  witness: ManagedPortfolioWitness | null;
}): ManagedPortfolioReconciliation {
  const { baseCurrency, members, witness } = input;

  const inBase = (value: MoneyMinor | null): number | null =>
    value !== null && value.currency === baseCurrency ? value.amountMinor : null;

  let investmentMinor = 0;
  let cashMinor = 0;
  let undetailedMinor = 0;
  let incompleteMembers = false;
  let investmentMemberCount = 0;

  for (const member of members) {
    const amountMinor = inBase(member.value);
    if (member.isUndetailed) {
      undetailedMinor += amountMinor ?? 0;
    }
    if (member.isCash) {
      // The cash box is reported, not careed: an unconvertible cash sibling
      // leaves the reported figure short but never blocks the careo, because the
      // careo does not read it.
      cashMinor += amountMinor ?? 0;
      continue;
    }
    investmentMemberCount += 1;
    if (amountMinor === null) {
      incompleteMembers = true;
      continue;
    }
    investmentMinor += amountMinor;
  }

  const investmentValue: MoneyMinor = {
    amountMinor: investmentMinor,
    currency: baseCurrency,
  };
  const cashValue: MoneyMinor = { amountMinor: cashMinor, currency: baseCurrency };
  const base = {
    cashValue,
    investmentValue,
    thresholdBps: MANAGED_PORTFOLIO_DRIFT_THRESHOLD_BPS,
    undetailedValue: { amountMinor: undetailedMinor, currency: baseCurrency },
  };

  if (witness === null) {
    return {
      ...base,
      declaredDate: null,
      declaredValue: null,
      driftBps: null,
      state: "no_witness",
    };
  }

  const declared = {
    declaredDate: witness.declaredDate,
    declaredValue: witness.declaredValue,
  };

  if (witness.declaredValue.currency !== baseCurrency) {
    return {
      ...base,
      ...declared,
      driftBps: null,
      reason: "currency_mismatch",
      state: "not_comparable",
    };
  }
  if (incompleteMembers) {
    return {
      ...base,
      ...declared,
      driftBps: null,
      reason: "incomplete_members",
      state: "not_comparable",
    };
  }
  if (witness.declaredValue.amountMinor <= 0) {
    return {
      ...base,
      ...declared,
      driftBps: null,
      reason: "declared_not_positive",
      state: "not_comparable",
    };
  }
  if (investmentMemberCount === 0) {
    return {
      ...base,
      ...declared,
      driftBps: null,
      reason: "no_investment_value",
      state: "not_comparable",
    };
  }

  const declaredMinor = witness.declaredValue.amountMinor;
  const gapMinor = investmentMinor - declaredMinor;
  // The verdict is decided on integers (`|gap| × 10.000 > bps × declared`) so a
  // figure sitting exactly on the threshold cannot flip with float noise; the
  // reported `driftBps` is the rounded reading of the same ratio.
  const diverged =
    Math.abs(gapMinor) * 10_000 > MANAGED_PORTFOLIO_DRIFT_THRESHOLD_BPS * declaredMinor;

  return {
    ...base,
    ...declared,
    driftBps: Math.round((gapMinor * 10_000) / declaredMinor),
    state: diverged ? "diverged" : "aligned",
  };
}

/** The drift as an es-ES percentage with one decimal, signed ("−1,2 %"). */
export function formatDriftBps(driftBps: number): string {
  const sign = driftBps < 0 ? "−" : "+";
  const percent = (Math.abs(driftBps) / 100).toFixed(1).replace(".", ",");
  return `${sign}${percent} %`;
}

/**
 * The human sentence a diverged careo carries into the data-health inventory
 * (#654 vocabulary). It names the portfolio, prints both figures and the drift,
 * and says out loud that the cash is outside the comparison — otherwise the
 * reader would try to reconcile the sentence against the ficha's total and find
 * the cash missing.
 */
export function describeManagedPortfolioDrift(input: {
  portfolioName: string;
  reconciliation: ManagedPortfolioReconciliation;
  privacyMode?: boolean;
}): string {
  const { portfolioName, reconciliation } = input;
  const privacyMode = input.privacyMode ?? false;
  const amount = (value: MoneyMinor) => formatMoneyMinorPrivacy(value, privacyMode);
  const declared = reconciliation.declaredValue;
  const drift = reconciliation.driftBps;

  if (declared === null || drift === null) {
    return `"${portfolioName}": el saldo declarado y el valor de sus fondos no se pueden comparar.`;
  }

  const opening =
    `"${portfolioName}": el valor de sus fondos (${amount(reconciliation.investmentValue)}) ` +
    `se aparta un ${formatDriftBps(drift)} del saldo que declaraste el ` +
    `${formatDateKeyEs(reconciliation.declaredDate ?? "")} (${amount(declared)}). `;

  // Mid-substitution the aggregate IS the explanation (#1551): it still stands
  // for a composition the owner has begun to detail, so the book counts the same
  // money twice until he shrinks it. Sending him to check prices instead would be
  // sending him to look for a problem that is not there.
  if (
    drift > 0 &&
    reconciliation.undetailedValue.amountMinor > 0 &&
    reconciliation.investmentValue.amountMinor > declared.amountMinor
  ) {
    return (
      `${opening}Tienes ${amount(reconciliation.undetailedValue)} sin detallar en su ` +
      "agregado: mientras represente lo que ya has detallado aparte, el libro cuenta " +
      "ese dinero dos veces. Reduce el agregado a lo que quede del saldo declarado. " +
      `El efectivo de la cartera (${amount(reconciliation.cashValue)}) queda fuera del careo.`
    );
  }

  return (
    `${opening}Manda el derivado: ` +
    `revisa participaciones, precios o el propio saldo declarado. El efectivo de la ` +
    `cartera (${amount(reconciliation.cashValue)}) queda fuera del careo.`
  );
}
