/**
 * Batched statement ripple (issue #174, ADR 0018 / ADR 0012).
 *
 * A statement load creates many backdated operations at once. Rippling them one
 * at a time would re-derive history N times — the O(N×snapshots) cliff behind
 * #158. `recordOperationsAndRipple` is the batched seam: it persists every
 * created/overwritten operation, generates a snapshot at each affected operation
 * date, then runs a SINGLE forward recalculation from the earliest date.
 *
 * These tests pin two things:
 *   1. BEHAVIOR — a multi-date load lands one snapshot per operation date and
 *      folds the operated asset forward across the whole band exactly once.
 *   2. READ SHAPE — the number of `snapshot_holdings` SELECTs is BOUNDED per
 *      scope (a small constant), independent of how many operation dates the load
 *      carries — proving one rebuild, not one-per-operation.
 */
import Database from "better-sqlite3";
import { describe, expect, test } from "vitest";

import { createStoreFromSqlite } from "@db/index";
import type { WorthlineStore } from "@db/index";

const TODAY = "2026-06-12";

function addDays(from: string, count: number): string {
  const d = new Date(`${from}T00:00:00.000Z`);
  d.setUTCDate(d.getUTCDate() + count);
  return d.toISOString().slice(0, 10);
}

function createCountingStore(): {
  store: WorthlineStore;
  holdingReads: () => number;
  reset: () => void;
} {
  let count = 0;
  const sqlite = new Database(":memory:", {
    verbose: (message?: unknown) => {
      if (typeof message === "string" && /\bsnapshot_holdings\b/i.test(message)) {
        if (/^\s*select/i.test(message)) count += 1;
      }
    },
  });
  const store = createStoreFromSqlite(sqlite);
  return {
    holdingReads: () => count,
    reset: () => {
      count = 0;
    },
    store,
  };
}

function grossAt(store: WorthlineStore, dateKey: string): number | undefined {
  return store.snapshots
    .readSnapshots("household")
    .find((snap) => snap.dateKey === dateKey)?.grossAssets.amountMinor;
}

describe("recordOperationsAndRipple batched statement seam (#174)", () => {
  test("generates one snapshot per operation date and folds the asset forward once", () => {
    const { store } = createCountingStore();
    store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo indexado",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });

    // Three backdated buys on distinct past dates — the batched operations seam
    // persists them all and runs ONE ripple over the dates they touch.
    const dates = ["2024-03-01", "2024-04-01", "2024-05-01"];

    // No snapshots exist yet — the band is entirely generated by this one call.
    expect(store.snapshots.readSnapshots("household")).toHaveLength(0);

    store.recordOperationsAndRipple({
      assetId: "fund",
      creates: dates.map((dateKey, i) => ({
        assetId: "fund",
        currency: "EUR",
        executedAt: dateKey,
        id: `op_${i}`,
        kind: "buy",
        pricePerUnit: "100",
        units: "10",
      })),
      overwrites: [],
      today: TODAY,
    });

    // Exactly one snapshot per operation date.
    const household = store.snapshots.readSnapshots("household");
    expect(household.map((s) => s.dateKey).sort()).toEqual(dates);

    // The fund folds cumulatively: 10 units @ 100 = 1000.00 per buy, on each date
    // ≥ the buy. So 1×, 2×, 3× 1000.00 across the three dates.
    expect(grossAt(store, "2024-03-01")).toBe(1000_00);
    expect(grossAt(store, "2024-04-01")).toBe(2000_00);
    expect(grossAt(store, "2024-05-01")).toBe(3000_00);

    store.close();
  });

  test("reads frozen holdings in a bounded shape, independent of the operation count", () => {
    const { store, holdingReads, reset } = createCountingStore();
    store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    // A `seedfund` whose daily backdated buys build a long band of pre-existing
    // snapshots to recalculate against.
    store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "seedfund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo semilla",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });
    store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo indexado",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });

    const startDate = "2024-01-01";
    const snapshotCount = 40;
    for (let i = 0; i < snapshotCount; i += 1) {
      const dateKey = addDays(startDate, i);
      store.recordOperationAndRipple(
        {
          assetId: "seedfund",
          currency: "EUR",
          executedAt: dateKey,
          id: `seedop_${dateKey}`,
          kind: "buy",
          pricePerUnit: "100",
          units: "1",
        },
        { today: TODAY },
      );
    }
    expect(store.snapshots.readSnapshots("household")).toHaveLength(snapshotCount);
    const scopeCount = store.snapshots
      .readSnapshots()
      .reduce((acc, snap) => acc.add(snap.scopeId), new Set<string>()).size;

    // TEN backdated buys of `fund` on the first ten band days. The record persist
    // runs no `snapshot_holdings` SELECT, so resetting just before the seam call
    // still counts only the single batched ripple's reads.
    const creates = Array.from({ length: 10 }, (_, i) => {
      const dateKey = addDays(startDate, i);
      return {
        assetId: "fund",
        currency: "EUR",
        executedAt: dateKey,
        id: `fundop_${dateKey}`,
        kind: "buy" as const,
        pricePerUnit: "100",
        units: "10",
      };
    });

    reset();
    store.recordOperationsAndRipple({
      assetId: "fund",
      creates,
      overwrites: [],
      today: TODAY,
    });

    // BATCHED: a small constant of frozen-row reads per scope — NOT one per
    // operation date (would be ≥ 10 × scope) nor one per rippled snapshot.
    const reads = holdingReads();
    expect(reads).toBeLessThanOrEqual(scopeCount * 4);
    expect(reads).toBeLessThan(snapshotCount);

    // BEHAVIOR across the whole band: seedfund folds (i+1)×100.00; fund folds
    // min(i+1, 10)×1000.00 (its ten buys are on days 0..9).
    const seedAt = (i: number): number => (i + 1) * 100_00;
    const fundAt = (i: number): number => Math.min(i + 1, 10) * 1000_00;
    for (let i = 0; i < snapshotCount; i += 1) {
      expect(grossAt(store, addDays(startDate, i))).toBe(seedAt(i) + fundAt(i));
    }

    store.close();
  });
});
