/**
 * Batched statement ripple (issue #174, ADR 0018 / ADR 0012).
 *
 * A statement load creates many backdated operations at once. Rippling them one
 * at a time would re-derive history N times — the O(N×snapshots) cliff behind
 * #158. `recordOperationsAndRipple` is the batched seam: it persists every
 * created/overwritten operation, generates a snapshot at each affected operation
 * date, then runs a SINGLE forward recalculation from the earliest date.
 *
 * These tests pin two things:
 *   1. BEHAVIOR — a multi-date load lands one snapshot per operation date and
 *      folds the operated asset forward across the whole band exactly once.
 *   2. READ SHAPE — the number of `snapshot_holdings` SELECTs is BOUNDED per
 *      scope (a small constant), independent of how many operation dates the load
 *      carries — proving one rebuild, not one-per-operation.
 */

import type { WorthlineStore } from "@db/index";
import { createStoreFromSqlite, openLibsqlClient } from "@db/index";
import type { Client, InStatement } from "@libsql/client";
import { describe, expect, test } from "vitest";

const TODAY = "2026-06-12";

function addDays(from: string, count: number): string {
  const d = new Date(`${from}T00:00:00.000Z`);
  d.setUTCDate(d.getUTCDate() + count);
  return d.toISOString().slice(0, 10);
}

/** The SQL text carried by a single libSQL statement. */
function statementSql(stmt: InStatement): string {
  return typeof stmt === "string" ? stmt : stmt.sql;
}

/**
 * Wrap a libSQL client so every statement reading `snapshot_holdings` is counted.
 * `client.execute` runs the store's individual reads (drizzle issues each
 * `db.select()` as one `execute`); `client.batch` runs grouped statements. We
 * inspect the SQL text of each and count only the SELECTs over the frozen rows.
 */
function countingClient(client: Client, bump: (sql: string) => void): Client {
  return new Proxy(client, {
    get(target, prop, receiver) {
      if (prop === "execute") {
        return (...args: Parameters<Client["execute"]>) => {
          const sql = typeof args[0] === "string" ? args[0] : statementSql(args[0]);
          bump(sql);
          return (target.execute as (...a: unknown[]) => unknown)(...args);
        };
      }
      if (prop === "batch") {
        return (...args: Parameters<Client["batch"]>) => {
          for (const stmt of args[0]) {
            bump(Array.isArray(stmt) ? stmt[0] : statementSql(stmt));
          }
          return (target.batch as (...a: unknown[]) => unknown)(...args);
        };
      }
      const value = Reflect.get(target, prop, receiver);
      return typeof value === "function" ? value.bind(target) : value;
    },
  }) as Client;
}

async function createCountingStore(): Promise<{
  store: WorthlineStore;
  holdingReads: () => number;
  snapshotWrites: () => number;
  reset: () => void;
}> {
  let readCount = 0;
  let writeCount = 0;
  const client = countingClient(openLibsqlClient(":memory:"), (message) => {
    if (/\bsnapshot_holdings\b/i.test(message)) {
      if (/^\s*select/i.test(message)) readCount += 1;
    }
    if (/^\s*insert\s+into\s+["`]?snapshots["`]?/i.test(message)) writeCount += 1;
  });
  const store = await createStoreFromSqlite(client);
  return {
    holdingReads: () => readCount,
    reset: () => {
      readCount = 0;
      writeCount = 0;
    },
    snapshotWrites: () => writeCount,
    store,
  };
}

async function grossAt(
  store: WorthlineStore,
  dateKey: string,
): Promise<number | undefined> {
  return (await store.snapshots.readSnapshots("household")).find(
    (snap) => snap.dateKey === dateKey,
  )?.grossAssets.amountMinor;
}

describe("recordOperationsAndRipple batched statement seam (#174)", () => {
  test("generates one snapshot per operation date and folds the asset forward once", async () => {
    const { store } = await createCountingStore();
    await store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    await store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo indexado",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });

    // Three backdated buys on distinct past dates — the batched operations seam
    // persists them all and runs ONE ripple over the dates they touch.
    const dates = ["2024-03-01", "2024-04-01", "2024-05-01"];

    // No snapshots exist yet — the band is entirely generated by this one call.
    expect(await store.snapshots.readSnapshots("household")).toHaveLength(0);

    await store.recordOperationsAndRipple({
      assetId: "fund",
      creates: dates.map((dateKey, i) => ({
        assetId: "fund",
        currency: "EUR",
        executedAt: dateKey,
        id: `op_${i}`,
        kind: "buy",
        pricePerUnit: "100",
        units: "10",
      })),
      overwrites: [],
      today: TODAY,
    });

    // Exactly one snapshot per operation date.
    const household = await store.snapshots.readSnapshots("household");
    expect(household.map((s) => s.dateKey).sort()).toEqual(dates);

    // The fund folds cumulatively: 10 units @ 100 = 1000.00 per buy, on each date
    // ≥ the buy. So 1×, 2×, 3× 1000.00 across the three dates.
    expect(await grossAt(store, "2024-03-01")).toBe(1000_00);
    expect(await grossAt(store, "2024-04-01")).toBe(2000_00);
    expect(await grossAt(store, "2024-05-01")).toBe(3000_00);

    store.close();
  });

  test("reads frozen holdings in a bounded shape, independent of the operation count", async () => {
    const { store, holdingReads, reset } = await createCountingStore();
    await store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    // A `seedfund` whose daily backdated buys build a long band of pre-existing
    // snapshots to recalculate against.
    await store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "seedfund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo semilla",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });
    await store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo indexado",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });

    const startDate = "2024-01-01";
    const snapshotCount = 40;
    for (let i = 0; i < snapshotCount; i += 1) {
      const dateKey = addDays(startDate, i);
      await store.recordOperationAndRipple(
        {
          assetId: "seedfund",
          currency: "EUR",
          executedAt: dateKey,
          id: `seedop_${dateKey}`,
          kind: "buy",
          pricePerUnit: "100",
          units: "1",
        },
        { today: TODAY },
      );
    }
    expect(await store.snapshots.readSnapshots("household")).toHaveLength(snapshotCount);
    const scopeCount = (await store.snapshots.readSnapshots()).reduce(
      (acc, snap) => acc.add(snap.scopeId),
      new Set<string>(),
    ).size;

    // TEN backdated buys of `fund` on the first ten band days. The record persist
    // runs no `snapshot_holdings` SELECT, so resetting just before the seam call
    // still counts only the single batched ripple's reads.
    const creates = Array.from({ length: 10 }, (_, i) => {
      const dateKey = addDays(startDate, i);
      return {
        assetId: "fund",
        currency: "EUR",
        executedAt: dateKey,
        id: `fundop_${dateKey}`,
        kind: "buy" as const,
        pricePerUnit: "100",
        units: "10",
      };
    });

    reset();
    await store.recordOperationsAndRipple({
      assetId: "fund",
      creates,
      overwrites: [],
      today: TODAY,
    });

    // BATCHED: a small constant of frozen-row reads per scope — NOT one per
    // operation date (would be ≥ 10 × scope) nor one per rippled snapshot.
    const reads = holdingReads();
    expect(reads).toBeLessThanOrEqual(scopeCount * 4);
    expect(reads).toBeLessThan(snapshotCount);

    // BEHAVIOR across the whole band: seedfund folds (i+1)×100.00; fund folds
    // min(i+1, 10)×1000.00 (its ten buys are on days 0..9).
    const seedAt = (i: number): number => (i + 1) * 100_00;
    const fundAt = (i: number): number => Math.min(i + 1, 10) * 1000_00;
    for (let i = 0; i < snapshotCount; i += 1) {
      expect(await grossAt(store, addDays(startDate, i))).toBe(seedAt(i) + fundAt(i));
    }

    store.close();
  });
});

describe("applyStatementImportAndRipple one-pass writes (#770)", () => {
  test("investment-only import still saves each affected snapshot exactly once", async () => {
    const { reset, snapshotWrites, store } = await createCountingStore();
    await store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    await store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });
    for (const [index, dateKey] of ["2024-01-01", "2024-02-01", "2024-03-01"].entries()) {
      await store.recordOperationAndRipple(
        {
          assetId: "fund",
          currency: "EUR",
          executedAt: dateKey,
          id: `seed_${index}`,
          kind: "buy",
          pricePerUnit: "100",
          units: "1",
        },
        { today: TODAY },
      );
    }

    reset();
    await store.applyStatementImportAndRipple({
      funds: [
        {
          assetId: "fund",
          creates: [
            {
              assetId: "fund",
              currency: "EUR",
              executedAt: "2024-01-01",
              id: "imported_investment",
              kind: "buy",
              pricePerUnit: "100",
              units: "1",
            },
          ],
          kind: "matched",
          overwrites: [],
        },
      ],
      today: TODAY,
    });

    const affected = (await store.snapshots.readSnapshots()).filter(
      ({ dateKey }) => dateKey >= "2024-01-01",
    );
    expect(snapshotWrites()).toBe(affected.length);
    store.close();
  });

  test("mixed investment, housing, and debt import saves every affected snapshot once", async () => {
    const { reset, snapshotWrites, store } = await createCountingStore();
    await store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    await store.assets.createInvestmentAsset({
      currency: "EUR",
      id: "fund",
      liquidityTier: "market",
      manualPricePerUnit: "100",
      name: "Fondo",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
    });
    await store.createHousingHoldingAndRipple(
      {
        acquisitionAnchor: {
          adjustsPriorCurve: true,
          assetId: "home",
          id: "home_acquisition",
          valuationDate: "2024-01-01",
          valueMinor: 200_000_00,
        },
        annualAppreciationRate: null,
        asset: {
          currency: "EUR",
          currentValueMinor: 200_000_00,
          id: "home",
          liquidityTier: "illiquid",
          name: "Vivienda",
          ownership: [{ memberId: "mJ", shareBps: 10_000 }],
          type: "real_estate",
        },
      },
      { today: TODAY },
    );
    await store.liabilities.createLiability({
      balanceMinor: 150_000_00,
      currency: "EUR",
      id: "mortgage",
      name: "Hipoteca",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
      type: "mortgage",
    });
    await store.liabilities.setDebtModel("mortgage", "amortizable");

    reset();
    await store.applyStatementImportAndRipple({
      balanceHistories: [
        {
          liabilityId: "mortgage",
          rebaselines: [
            {
              annualInterestRate: "0.03",
              baselineDate: "2024-02-01",
              endDate: "2024-05-01",
              id: "mixed_rebaseline",
              liabilityId: "mortgage",
              nextPaymentDate: "2024-03-01",
              outstandingBalanceMinor: 150_000_00,
              startsAtBaseline: true,
            },
          ],
        },
      ],
      funds: [
        {
          assetId: "fund",
          creates: [
            {
              assetId: "fund",
              currency: "EUR",
              executedAt: "2024-02-01",
              id: "mixed_operation",
              kind: "buy",
              pricePerUnit: "100",
              units: "1",
            },
          ],
          kind: "matched",
          overwrites: [],
        },
      ],
      propertyValuations: [
        {
          adjustsPriorCurve: true,
          assetId: "home",
          id: "mixed_appraisal",
          valuationDate: "2024-02-01",
          valueMinor: 220_000_00,
        },
      ],
      today: TODAY,
    });

    const affected = (await store.snapshots.readSnapshots()).filter(
      ({ dateKey }) => dateKey >= "2024-02-01",
    );
    expect(affected.length).toBeGreaterThan(1);
    expect(snapshotWrites()).toBe(affected.length);
    store.close();
  });
});
