/**
 * Action-level regression test for deleteAmortizationPlanAction (PRD #109 slice 10).
 *
 * RED test: the original implementation ripples with kind "amortizable-plan"
 * BEFORE deleting. Because that ripple kind early-returns when curve.plan is
 * null, calling it before delete recalculates snapshots with the plan still
 * present — and after the delete the snapshots remain frozen at plan-derived
 * balances. The action must instead delete first, then ripple with kind
 * "amortizable-revision" from the plan's startDate so existing snapshots are
 * re-valued against the now-planless curve (falls back to currentBalance).
 */
import { describe, expect, test } from "vitest";

import { createInMemoryStore } from "@worthline/db";
import type { WorthlineStore } from "@worthline/db";

import { deleteAmortizationPlanAction } from "./actions";

/** Build a FormData with the given key/value pairs. */
function form(entries: Record<string, string>): FormData {
  const fd = new FormData();
  for (const [key, value] of Object.entries(entries)) {
    fd.set(key, value);
  }
  return fd;
}

/**
 * Invoke an action that always throws `redirect()` and return the redirect URL.
 * Next.js redirect() throws an error with `message === "NEXT_REDIRECT"` whose
 * `digest` field carries the destination URL.
 */
async function runAction(
  action: (fd: FormData, store?: WorthlineStore) => Promise<never>,
  fd: FormData,
  store: WorthlineStore,
): Promise<string> {
  try {
    await action(fd, store);
    throw new Error("action did not redirect");
  } catch (err: unknown) {
    const e = err as { message?: string; digest?: string };
    if (e.message === "NEXT_REDIRECT" && typeof e.digest === "string") {
      return e.digest;
    }
    throw err;
  }
}

/** Debt total in a snapshot at the given dateKey (household / default scope). */
function debtsAt(store: WorthlineStore, dateKey: string): number | undefined {
  return store.snapshots.readSnapshots().find((s) => s.dateKey === dateKey)?.debts
    .amountMinor;
}

const TODAY = new Date().toISOString().slice(0, 10);

describe("deleteAmortizationPlanAction — ripple correctness", () => {
  function seedStore(): WorthlineStore {
    const store = createInMemoryStore();
    store.workspace.initializeWorkspace({
      members: [{ id: "mJ", name: "Jose" }],
      mode: "individual",
    });
    store.assets.createManualAsset({
      currency: "EUR",
      currentValueMinor: 10_000_00,
      id: "cash",
      liquidityTier: "cash",
      name: "Cuenta",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
      type: "cash",
    });
    store.liabilities.createLiability({
      balanceMinor: 100_000_00,
      currency: "EUR",
      id: "mortgage",
      name: "Hipoteca",
      ownership: [{ memberId: "mJ", shareBps: 10_000 }],
      type: "mortgage",
    });
    store.liabilities.setDebtModel("mortgage", "amortizable");
    return store;
  }

  test("after deleting a plan, existing historical snapshots reflect currentBalance (not the plan balance)", async () => {
    const store = seedStore();

    // Use a fixed past start date so snapshot dates are deterministic regardless
    // of when this test runs.
    store.liabilities.createAmortizationPlan({
      annualInterestRate: "0.03",
      id: "plan1",
      initialCapitalMinor: 150_000_00,
      liabilityId: "mortgage",
      startDate: "2026-01-15",
      termMonths: 240,
    });

    // Ripple to generate plan-derived historical snapshots.
    store.rippleHistoricalSnapshotsForDebt({
      liabilityId: "mortgage",
      kind: "amortizable-plan",
      today: TODAY,
    });

    // Pre-condition: at least one snapshot exists with a plan-derived balance
    // (which is ≠ currentBalance of 100_000_00).
    const planBalance = store.liabilities.debtBalanceAtDate("mortgage", "2026-01-15");
    expect(planBalance).not.toBe(100_000_00);
    expect(debtsAt(store, "2026-01-15")).toBe(planBalance);

    // Invoke the action.
    await runAction(
      deleteAmortizationPlanAction,
      form({ id: "mortgage", planId: "plan1" }),
      store,
    );

    // After the action, every snapshot that was generated by the plan must now
    // reflect the currentBalance (100_000_00) — because with no plan the debt
    // curve falls back to the last-known current balance.
    for (const dateKey of [
      "2026-01-15",
      "2026-02-15",
      "2026-03-15",
      "2026-04-15",
      "2026-05-15",
    ]) {
      const snapshotDebt = debtsAt(store, dateKey);
      if (snapshotDebt !== undefined) {
        expect(snapshotDebt).toBe(100_000_00);
      }
    }

    store.close();
  });
});
